version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    ports:
      - 8005:8080
    volumes:
      - ./app:/app
      - ./logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
       - db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    restart: always

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
       REDIS_1_HOST: redis
    ports:
      - 8889:80