<?php

namespace App\Tests\Core\Infrastructure\Service\AggregateDate;


use App\Core\Infrastructure\Service\AggregateDate\SortDayMonth;
use PHPUnit\Framework\TestCase;

class SortDayMonthTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testShouldReturnLastDayOfMonth()
    {
        $dateTime = new \DateTime();

        $date = date('t', strtotime($dateTime->format('Y-m')));
        $result = SortDayMonth::lastDayOfMonth();

        $this->assertEquals($date, $result);
    }

}